{
    "setup": {
        "segmentation": "GeneralSegmentation",
        "model_to_use": "CustomCellpose"
    },

    "service": {
        "runner_name": "bento_runner",
        "bento_model_path": "cells",   
        "service_name": "data-centric-platform",
        "port": 7010
    },

    "model": { 
        "segmentor": {
            "model_type": "cyto"
        }
    },

    "data": {
        "data_root": "data",
        "accepted_types": [".jpg", ".jpeg", ".png", ".tiff", ".tif"],
        "seg_name_string": "_seg",
        "gray": True,
        "rescale": True
    },

    "eval":{
        "segmentor": {
            "z_axis": null,
            "channel_axis": null,
            "rescale": 1,
            "batch_size": 1
        },
        "mask_channel_axis": null
    }
}