{
    "setup": {
        "segmentation": "GeneralSegmentation",
        "model_to_use": "Inst2MultiSeg"
    },

    "service": {
        "runner_name": "bento_runner",
        "bento_model_path": "cells",
        "service_name": "SegmentationService",
        "port": 7010,
        "timeout": 1000,
    },

    "model": { 
        "segmentor_name": "Cellpose",
        "segmentor": {
            "model_type": "cyto"
            
        },
        "classifier_name": "PatchClassifier",
        "classifier":{
            "in_channels": 1,
            "num_classes": 2,
            "features":[64,128,256,512],
            "black_bg": False,
            "include_mask": True
        }
    },

    "data": {
        "data_root": "data",
        "accepted_types": [".jpg", ".jpeg", ".png", ".tiff", ".tif"],
        "seg_name_string": "_seg",
        "patch_size": 64,
        "noise_intensity": 5,
        "gray": True,
        "rescale": True
    },

    "eval":{
        "segmentor": {
            "z_axis": null,
            "channel_axis": null,
            "rescale": 1,
            "batch_size": 1
        },
        "classifier": {
        },
        "mask_channel_axis": 0
    }
}